### ISSUE TITLE
pacx auth create examples?

### ISSUE THREAD

**Issue by kevinvanrooij** [neronotte/Greg.Xrm.Command#60]
It would be nice to have some examples for commands. I am trying to authenticate with my environment using 'pacx auth create' but encounter several errors. 

Examples:
- Test with AuthType Office365: `pacx auth create --name 'name' --conn 'AuthType=Office365;Url=https://<organization>.crm4.dynamics.com;Username=username@domain.tld'`. Result: "_AuthType is invalid.  Please see Microsoft.PowerPlatform.Dataverse.Client.AuthenticationType for supported authentication types. (Parameter 'AuthType')_" - probably related to [Deprecation of Office365 authentication type](https://learn.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse)?
- Test with OAuth: `pacx auth create --name 'name' --conn 'AuthType=OAuth;Url=https://<organization>.crm4.dynamics.com;Username=username@domain.tld'`. Result: " _Failed to connect to Dataverse
  Only loopback redirect uri is supported, but app://\<GUID\>was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details_"

The 'normal' `pac auth create` (not `pacx`) command without parameters displays the login pop-up box. Could this be achieved for `pacx` as well?

**Comment by neronotte** [comment]
Hi kevin,
thanks for yous ask.

`pacx auth create` command accepts any valid dataverse connection strings. Dataverse connection string format is fully [documented here](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect). I don't think that I will replicate the contents here, to avoid misalignment, but I could add a pointer to the official MS document in order to streamline usage of the tool.

If you want to open the standard login popup box just type a connection string like this one:

```
AuthType=OAuth;Url=https://<myorg>.crm4.dynamics.com;RedirectUri=http://localhost
```

But I haven't found a way (yet) to save the credentials you provide in that login windows as `pac` or `XrmToolBox` does... Any pull request in that direction is appreciated!

Let me know if this fits your needs.

**Comment by westerdaled** [comment]
I have a similar issue: thought I would test against my dev tenant:

` pacx auth create --name "Daniel 2" --conn AuthType=OAuth;Url=https://org041XXXXX.crm11.dynamics.com;UserName=daniel@mytenant.onmicrosoft.com`

_Object reference not set to an instance of an object._

**Comment by neronotte** [comment]
Hi @westerdaled,
yes please, any info would be helpful.

**Comment by westerdaled** [comment]
Ok , can you message me on daniel@westerdale.biz  and I will resend the actual error messages .

**Comment by westerdaled** [comment]
Here is the current error in the latest version

```
pacx auth create --name "Daniel  2" --conn AuthType=OAuth;Url=https://org041XXXX.crm11.dynamics.com;RedirectUri=http://localhost

Version 1.2024.6.138
Online documentation: https://github.com/neronotte/Greg.Xrm.Command/wiki
Feedback, Suggestions, Issues: https://github.com/neronotte/Greg.Xrm.Command/discussions

Object reference not set to an instance of an object.

Url=https://org041dXXXXX.crm11.dynamics.com: The term 'Url=https://org041XXXX.crm11.dynamics.com' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
RedirectUri=http://localhost: The term 'RedirectUri=http://localhost' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by westerdaled** [comment]
Ok  I thought I would use the alternate syntax.  I used  `pac admin create-service-principal -` to create my service principal to connect my personal environment 

```
pacx auth create --name "Daniel Personal 2" --conn AuthType=ClientSecret;Url=https://org041XXXXX.crm11.dynamics.co
m;ClientId=myAppId;ClientSecret=mySecretValue
```
Version 1.2024.6.139
Online documentation: https://github.com/neronotte/Greg.Xrm.Command/wiki
Feedback, Suggestions, Issues: https://github.com/neronotte/Greg.Xrm.Command/discussions

Object reference not set to an instance of an object.

Url=https://orgXXXX.crm11.dynamics.com: The term 'Url=https://orgXXXX.crm11.dynamics.com' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ClientId=????: The term 'ClientId=????' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by neronotte** [comment]
Yes, it seems that the semicolon breaks the flow for the terminal, thus everything after is assumed to be another instruction.
I'm currently investigating the "Object reference.." error, it should not be thrown in any case. 
I will also add a note in the docs to clarify the importance of double quotes in the connection string
