### ISSUE TITLE
Implement update for poly relationship

### ISSUE THREAD

**Issue by magesoe** [neronotte/Greg.Xrm.Command#87]
Should be very similar to https://github.com/neronotte/Greg.Xrm.Command/wiki/pacx-rel-create-poly

But should use this https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/multitable-lookup#add-relationship-to-existing-polymorphic-lookup-example-payload

**Comment by neronotte** [comment]
Almost a month later (sorry for the delay) I've pushed the command you requested:

```Powershell
pacx rel poly add --child childtable --parent parenttable --lookupColumn new_parenttableid
pacx rel poly add -c childtable -p parenttable -l new_parenttableid
```

And also the dual

```Powershell
pacx rel poly remove --child childtable --parent parenttable --lookupColumn new_parenttableid
pacx rel poly remove -c childtable -p parenttable -l new_parenttableid
```

Check latest pacx version and let me know what do you think about it!

[Command help here](https://github.com/neronotte/Greg.Xrm.Command/wiki/pacx-rel-poly)
